name: Activity Summary

on:
  schedule:
    - cron: '30 7 * * 0'
  workflow_dispatch:
    inputs:
      test_address:
        description: 'The address to receive digests'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r github-notify-ml/requirements.txt
        pip install -r requirements.txt
    - name: run script
      env:
        GH_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SMTP_HOST: email-smtp.us-east-1.amazonaws.com
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_SSL: TRUE
        TEST_ADDRESS: ${{ github.event.inputs.test_address }}
      run: |
        python main.py send
